---

- name: Create Infrastructure
  hosts: local

  vars_files:
    - vars/aws-config.yml

  roles:
  - setup-vpc
  - setup-security-groups
  - setup-virtual-machines
  - setup-dns
  - setup-ssh
  - setup-host-groups

  pre_tasks:
    - name: Verify Ansible Version
      assert:
        that: 
          - "ansible_version.major == 2"
          - "ansible_version.minor == 4"
        msg: "This script is only supported with the 2.4 version of Ansible"
    
    - fail: msg="Variables required to register subscriptions are missing, please confirm that either rhsm_username, rhsm_password and rhsm_pool OR rhsm_key_id and rhsm_org_id is defined"
      when: (deployment_type == 'openshift-enterprise') and not (((rhsm_username is defined) and (rhsm_password is defined) and (rhsm_pool is defined)) or ((rhsm_key_id is defined) and (rhsm_org_id is defined)))


- name: Setup VM hosts
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

- name: Register and update virtual machines
  hosts: created_vms
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  vars:
    state: 'present'

  roles:    

  #- {role: register-virtual-machines, when: deployment_type == 'openshift-enterprise'}
  #- update-virtual-machines

#############################################################
# Openshift Prerequisites
#############################################################
- name: Setup Node hosts
  hosts: localhost

  vars_files:
    - vars/aws-config.yml

- name: OpenShift Prerequisites
  hosts: created_nodes
  remote_user: "{{ amazon_user }}"

  vars_files:
    - vars/aws-config.yml

  vars:
    state: 'present'

  roles:
   #- openshift-pre-reqs

#############################################################
# Install Openshift
#############################################################
- name: Install OpenShift
  hosts: local

  vars_files:
    - vars/aws-config.yml

  vars:
#    nodes_ip: "{{ lookup('file','nodes.json') | from_json }}"
    state: 'present'

  roles:
  - openshift-install
  - add-users
  - openshift-post-install

  post_tasks:
   - name: Confirmation message
     debug:
      msg: 
        - 'The script has completed successfully.'
        - 'Master public IP: {{master_public_ip}}'
        - 'OpenShift console: https://{{public_dns_zone}}:8443'
