---

- name: install pre-req packages on bastion
  yum:
    name:
      - "git"
      - "@Development Tools"
      - "openssl-devel"
      - "python-devel"
      - "gcc"
      - "libffi-devel"
      - "ansible"
      - "atomic-openshift-utils"
    state: "present"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  become: true
  when: deployment_type == 'origin'

- name: install pre-req packages on bastion
  yum:
    name:
      - "atomic-openshift-utils"
    state: "present"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  become: true
  when: deployment_type != 'origin'

- name: copy inventory for openshift istallation
  template:
    src: "../files/openshift_inventory.cfg"
    dest: "~{{amazon_user}}/openshift_inventory.cfg"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: checkout openshift ansible repo on bastion
  git:
    repo: "https://github.com/openshift/openshift-ansible"
    dest: "~{{amazon_user}}/openshift-ansible"
    version: "{{openshift_branch}}"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  when: deployment_type == 'origin'

- name: copy script for openshift istallation
  template:
    src: "../files/install-openshift.sh"
    dest: "~{{amazon_user}}/install-openshift.sh"
    mode: "0775"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: provide details to check installation
  debug:
   msg: "Check file install-openshift.log in Bastion 'ssh ec2-user@{{bastion_public_ip}}' "

- name: run openshift installation script
  shell: 'timeout 30m ./install-openshift.sh {{deployment_type}} |& tee install-openshift.log'
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  async: 1800
  poll: 5  

